# Generated by Django 3.0.7 on 2021-01-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrouterdetails',
            name='sapId',
            field=models.CharField(default=None, max_length=18),
        ),
    ]
